// Contract ABI - Generated after compiling the smart contract
// This will be auto-generated by Hardhat, but we define the interface here

export const CONTRACT_ABI = [
    {
        "inputs": [
            { "internalType": "string", "name": "credentialId", "type": "string" },
            { "internalType": "bytes32", "name": "dataHash", "type": "bytes32" },
            { "internalType": "string", "name": "ipfsCid", "type": "string" }
        ],
        "name": "issueCredential",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "inputs": [
            { "internalType": "string", "name": "credentialId", "type": "string" }
        ],
        "name": "getCredential",
        "outputs": [
            { "internalType": "bytes32", "name": "dataHash", "type": "bytes32" },
            { "internalType": "string", "name": "ipfsCid", "type": "string" },
            { "internalType": "address", "name": "issuer", "type": "address" },
            { "internalType": "uint256", "name": "timestamp", "type": "uint256" },
            { "internalType": "bool", "name": "exists", "type": "bool" }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "inputs": [
            { "internalType": "string", "name": "credentialId", "type": "string" },
            { "internalType": "bytes32", "name": "dataHash", "type": "bytes32" }
        ],
        "name": "verifyCredential",
        "outputs": [
            { "internalType": "bool", "name": "isValid", "type": "bool" }
        ],
        "stateMutability": "nonpayable",
        "type": "function"
    },
    {
        "inputs": [
            { "internalType": "string", "name": "credentialId", "type": "string" }
        ],
        "name": "credentialExists",
        "outputs": [
            { "internalType": "bool", "name": "", "type": "bool" }
        ],
        "stateMutability": "view",
        "type": "function"
    },
    {
        "anonymous": false,
        "inputs": [
            { "indexed": true, "internalType": "string", "name": "credentialId", "type": "string" },
            { "indexed": false, "internalType": "bytes32", "name": "dataHash", "type": "bytes32" },
            { "indexed": false, "internalType": "string", "name": "ipfsCid", "type": "string" },
            { "indexed": true, "internalType": "address", "name": "issuer", "type": "address" },
            { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }
        ],
        "name": "CredentialIssued",
        "type": "event"
    },
    {
        "anonymous": false,
        "inputs": [
            { "indexed": true, "internalType": "string", "name": "credentialId", "type": "string" },
            { "indexed": false, "internalType": "bool", "name": "isValid", "type": "bool" },
            { "indexed": false, "internalType": "uint256", "name": "timestamp", "type": "uint256" }
        ],
        "name": "CredentialVerified",
        "type": "event"
    }
];

export const getContractConfig = () => {
    return {
        address: process.env.CONTRACT_ADDRESS || '',
        abi: CONTRACT_ABI,
    };
};
